### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by azer67**
- Ancient Sea Chart unlocks Ship Dowsing
- Removed talk triggers from Mogmas in Skyview 2 (except the first one)
- Removed Fi Text in front of LMF Boss Door
- Removed a soil patch in the tree eye room of Skyview 2 that can block the box

### CODE REVIEW

**Comment by azer67** [comment]
I don't know very much about github, the goddess crest removal in the Goddess Statue was done by pepper on master, but also by this branch, so make sure it's not getting duplicated or something

**Comment by azer67** [comment]
Owlan's quest now completely works except he doesn't give the item at the end. I'm not sure why so I left it commented in the item location file

**Comment by azer67** [comment]
Alright now Owlan is randomized and works (thx pepper). The conflict is because pepper did half of the fix already but this pull request does the rest.
Also fixed the Academy billboard, sort of. I think there is still a problem when having LMF, FS, AC and ET (because "Ancient Cistern, Earth Temple" is one character too long), but I don't really know how to fix it.

**Comment by lepelog** [comment]
Very nice, I changed the fix for the length a bit, so it breaks them up at whitespaces dynamically

**Pull request merged**
